# Generated by Django 2.2.2 on 2019-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msarif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
