# Generated by Django 2.2.2 on 2019-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msarif', '0002_auto_20190622_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
